name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: true
        default: 'v0.0.1'

jobs:
  build:
    permissions:
      contents: write
      packages: read
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: macos
            arch: arm64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
          
      - name: Setup Windows Build Environment
        if: runner.os == 'Windows'
        run: |
          choco install wixtoolset -y
          choco install bonjour -y
          choco install openssl -y
          
      - uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'
        with:
          msbuild-architecture: x64
          
      - name: Configure NuGet
        if: runner.os == 'Windows'
        env:
          NugetCredentials: "Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "NuGetPackageSourceCredentials_gh-ikvmnet=${{ env.NugetCredentials }}" >> $env:GITHUB_ENV
          echo "NuGetPackageSourceCredentials_gh-iterate-ch=${{ env.NugetCredentials }}" >> $env:GITHUB_ENV
          
      - name: Build All Platforms
        run: |
          # Use standard Maven build which handles all platforms
          mvn --batch-mode clean package -DskipTests -DskipSign -DskipNotarize
          
      - name: Build Windows Installer
        if: runner.os == 'Windows'
        continue-on-error: true
        shell: pwsh
        run: |
          # Windows GUI needs proper packaging with dependencies
          cd windows
          # Build the full installer package which includes all dependencies
          mvn --batch-mode package -DskipTests -DskipSign || echo "Windows installer build failed"
        
      - name: Find and Display Build Artifacts
        shell: bash
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Looking for all target directories ==="
          find . -type d -name "target" | head -20
          echo "=== Looking for build artifacts ==="
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "=== Windows build artifacts ==="
            find . -name "*.exe" -size +1M -ls | head -20
            find . -name "*.msi" -ls | head -20
            ls -la cli/windows/target/Release/ 2>/dev/null || echo "No CLI Release build"
            ls -la windows/target/ 2>/dev/null || echo "No GUI build"
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            echo "=== Linux build artifacts ==="
            find . -name "duck" -type f -ls | head -20
            find . -name "*.jar" -size +10M -ls | head -10
            ls -la cli/target/ 2>/dev/null || echo "No CLI target"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "=== macOS build artifacts ==="
            find . -name "*.app" -o -name "*.dmg" -o -name "*.pkg" | head -20
            find . -name "duck.bundle" -type d | head -10
            ls -la osx/target/ 2>/dev/null || echo "No OSX target"
            ls -la cli/osx/target/ 2>/dev/null || echo "No CLI OSX target"
          fi
          
      - name: Upload Build Artifact - macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-build
          path: |
            osx/target/*.dmg
            osx/target/*.pkg
            cli/osx/target/duck.bundle/**
            cli/osx/target/*.zip
          if-no-files-found: warn
          
      - name: Upload Build Artifact - Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-build
          path: |
            cli/target/duck
            cli/linux/target/duck
            cli/target/*.jar
            **/target/*.jar
          if-no-files-found: warn
          
      - name: Upload Build Artifact - Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-build
          path: |
            cli/windows/target/Release/*.exe
            cli/windows/target/Release/*.msi
            windows/target/Cyberduck.exe
            windows/target/*.dll
          if-no-files-found: warn
          
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: Display structure of downloaded files
        run: |
          echo "=== All artifacts ==="
          ls -la ./artifacts/
          echo "=== Contents of each artifact ==="
          for dir in ./artifacts/*/; do
            echo "Contents of $dir:"
            ls -la "$dir"
          done
        
      - name: Package artifacts
        run: |
          mkdir -p release-assets
          
          # Package macOS
          echo "=== Processing macOS artifacts ==="
          if [ -d "./artifacts/macos-arm64-build" ]; then
            # Look for duck.bundle
            bundle=$(find ./artifacts/macos-arm64-build -name "duck.bundle" -type d | head -1)
            if [ -n "$bundle" ]; then
              echo "Found bundle at: $bundle"
              cd $(dirname "$bundle")
              zip -r Cyberduck-macos-arm64.zip $(basename "$bundle")
              mv Cyberduck-macos-arm64.zip $GITHUB_WORKSPACE/release-assets/
              cd $GITHUB_WORKSPACE
            fi
            # Look for DMG/PKG if exists
            dmg=$(find ./artifacts/macos-arm64-build -name "*.dmg" | head -1)
            if [ -n "$dmg" ]; then
              echo "Found DMG at: $dmg (size: $(du -h "$dmg" | cut -f1))"
              cp "$dmg" ./release-assets/Cyberduck-macos-arm64.dmg
            fi
          fi
          
          # Package Linux
          echo "=== Processing Linux artifacts ==="
          if [ -d "./artifacts/linux-x64-build" ]; then
            # Look for duck executable
            duck=$(find ./artifacts/linux-x64-build -name "duck" -type f | head -1)
            if [ -n "$duck" ]; then
              echo "Found duck at: $duck (size: $(du -h "$duck" | cut -f1))"
              # Create a simple launcher script for GUI
              echo '#!/bin/bash' > ./release-assets/Cyberduck-linux-x64.sh
              echo '# Cyberduck GUI launcher for Linux' >> ./release-assets/Cyberduck-linux-x64.sh
              echo 'java -jar "$(dirname "$0")/Cyberduck-linux-x64.jar" "$@"' >> ./release-assets/Cyberduck-linux-x64.sh
              chmod +x ./release-assets/Cyberduck-linux-x64.sh
            fi
            # Look for main JAR file
            jar=$(find ./artifacts/linux-x64-build -name "*.jar" -size +10M | grep -v test | head -1)
            if [ -n "$jar" ]; then
              echo "Found JAR at: $jar (size: $(du -h "$jar" | cut -f1))"
              cp "$jar" ./release-assets/Cyberduck-linux-x64.jar
            fi
          fi
          
          # Package Windows
          echo "=== Processing Windows artifacts ==="
          if [ -d "./artifacts/windows-x64-build" ]; then
            # Priority 1: Look for MSI installer (complete package)
            msi=$(find ./artifacts/windows-x64-build -name "*.msi" -size +10M | head -1)
            if [ -n "$msi" ]; then
              echo "Found MSI installer at: $msi (size: $(du -h "$msi" | cut -f1))"
              cp "$msi" ./release-assets/Cyberduck-Installer-windows-x64.msi
            fi
            
            # Priority 2: Look for setup exe (alternative installer)
            setup=$(find ./artifacts/windows-x64-build -name "*etup*.exe" -o -name "*nstaller*.exe" | grep -v ".msi" | head -1)
            if [ -n "$setup" ]; then
              echo "Found setup exe at: $setup (size: $(du -h "$setup" | cut -f1))"
              cp "$setup" ./release-assets/Cyberduck-Setup-windows-x64.exe
            fi
            
            # Priority 3: CLI executable from Release folder
            cli_exe=$(find ./artifacts/windows-x64-build -path "*/Release/*.exe" -size +10M | grep -v -E "(Setup|Installer)" | head -1)
            if [ -n "$cli_exe" ]; then
              echo "Found CLI exe at: $cli_exe (size: $(du -h "$cli_exe" | cut -f1))"
              cp "$cli_exe" ./release-assets/duck-cli-windows-x64.exe
            fi
            
            # Note about GUI
            echo "Note: Windows GUI requires .NET Framework 4.7.2 and should be installed via MSI installer"
          fi
          
          # List final assets
          echo "=== Final release assets ==="
          ls -la ./release-assets/
          
          # Create README for the release
          {
            echo "# Cyberduck Release"
            echo ""
            echo "## Windows"
            echo "- **Cyberduck-Installer-windows-x64.msi** - Full installer with GUI (recommended)"
            echo "- **duck-cli-windows-x64.exe** - Command-line version (60MB standalone)"
            echo ""
            echo "### Windows Requirements:"
            echo "- .NET Framework 4.7.2 or later"
            echo "- Windows 7 SP1 or later"
            echo ""
            echo "## macOS"
            echo "- **Cyberduck-macos-arm64.zip** - macOS application bundle for M1/M2/M3/M4 chips"
            echo "- **Cyberduck-macos-arm64.dmg** - Disk image installer (if available)"
            echo ""
            echo "## Linux"
            echo "- **Cyberduck-linux-x64.jar** - Java-based GUI application"
            echo "- **Cyberduck-linux-x64.sh** - Launcher script"
            echo ""
            echo "### Linux Requirements:"
            echo "- Java 11 or later"
            echo "- Run with: \`./Cyberduck-linux-x64.sh\` or \`java -jar Cyberduck-linux-x64.jar\`"
            echo ""
            echo "## Notes"
            echo "- Windows GUI requires the MSI installer for proper dependency installation"
            echo "- Linux version runs as a Java application"
            echo "- macOS version is optimized for Apple Silicon (M-series chips)"
          } > ./release-assets/README.md
          
          # Check if we have any assets
          if [ -z "$(ls -A ./release-assets | grep -v README)" ]; then
            echo "WARNING: No release artifacts found!"
            echo "Build artifacts not found. Check build logs." >> ./release-assets/README.md
          fi
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          name: Release ${{ github.event.inputs.tag_name || github.ref_name }}
          draft: false
          prerelease: false
          files: |
            release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}